### ISSUE TITLE
key :count not found

### ISSUE THREAD

**Issue by sclearion** [checkiz/elixir-mongo#17]
'coll.count' is returning a "key :count not found in %Mongo.Collection..." error. The block that throws this error looks like:?

coll = Mongo.connect! |> Mongo.db("clearion_api_dev") |> Mongo.Db.collection("users")
coll.count

Am i doing something wrong?

**Comment by jerp** [comment]
please try

``` elixir
iex> collection = Mongo.Helpers.test_collection("anycoll")
      ...> {:ok, 6} = collection |> Mongo.Collection.count
      ...> 6 === collection |> Mongo.Collection.count!
      true
```
